uav_ros_control: uav_reference::CarrotReference Class Reference
uav_reference::CarrotReference Class Reference
#include <CarrotReference.hpp>
Public Member Functions
CarrotReference (ros::NodeHandle &)
virtual ~CarrotReference ()
void updateCarrot ()
void publishCarrotSetpoint ()
void updateCarrotStatus ()
bool isCarrotEnabled ()
bool isHoldEnabled ()
Public Member Functions inherited from uav_reference::JoyControlInput
JoyControlInput (ros::NodeHandle &)
virtual ~JoyControlInput ()
double getXOffsetManual ()
double getYOffsetManual ()
double getZOffsetManual ()
double getRollSpManual ()
double getPitchSpManual ()
double getYawSpManual ()
double getThrustSpUnscaled ()
double getThrustScale ()
double getYawScale ()
const std::vector< int32_t > getJoyButtons ()
const std::vector< float > getJoyAxes ()
bool isJoyActive ()
Private Member Functions
void resetIntegrators ()
void initializeParameters ()
void updateCarrotXY (double x, double y)
void updateCarrotXY ()
void updateCarrotZ (double z)
void updateCarrotZ ()
void updateCarrotYaw ()
void resetCarrot ()
bool posHoldServiceCb (std_srvs::Empty::Request &request, std_srvs::Empty::Response &response)
bool takeoffServiceCb (uav_ros_control_msgs::TakeOff::Request &request, uav_ros_control_msgs::TakeOff::Response &response)
bool landServiceCb (std_srvs::SetBool::Request &request, std_srvs::SetBool::Response &response)
void positionRefCb (const trajectory_msgs::MultiDOFJointTrajectoryPointConstPtr &posMsg)
void odomCb (const nav_msgs::OdometryConstPtr &)
Private Attributes
trajectory_msgs::MultiDOFJointTrajectoryPoint _carrotPoint
std::array< double, 3 > _uavPos { 0.0, 0.0, 0.0 }
double _carrotYaw = 0
double _uavYaw = 0
bool _carrotEnabled = false
bool _positionHold = true
int _carrotEnabledIndex = -1
int _carrotEnabledValue = 1
bool _firstPass = true
bool _manualTakeoffEnabled = true
bool _carrotOnLand = false
bool _takeoffHappened = false
ros::Publisher _pubCarrotTrajectorySp
ros::Publisher _pubCarrotYawSp
ros::Publisher _pubUAVYaw
ros::Publisher _pubCarrotPose
ros::Publisher _pubCarrotStatus
ros::Subscriber _subOdom
ros::Subscriber _subPosHoldRef
ros_util::TopicHandler< mavros_msgs::State > m_handlerState
ros::ServiceServer _servicePoisitionHold
ros::ServiceServer _serviceTakeoff
ros::ServiceServer _serviceLand
ros::ServiceClient _intResetClient
ros::ServiceClient _setModeToLandClient
Detailed Description
"Carrot-on-a-Stick" reference publisher class. Reference is published with respect to the global coordinate system.
Definition at line 19 of file CarrotReference.hpp.
Constructor & Destructor Documentation
uav_reference::CarrotReference::CarrotReference (ros::NodeHandle & nh)
Default constructor. Used for reading ROS parameters and initalizing private variables.
Definition at line 17 of file CarrotReference.cpp.
References _carrotPoint, _intResetClient, _manualTakeoffEnabled, _positionHold, _pubCarrotPose, _pubCarrotStatus, _pubCarrotTrajectorySp, _pubCarrotYawSp, _pubUAVYaw, _serviceLand, _servicePoisitionHold, _serviceTakeoff, _setModeToLandClient, _subOdom, _subPosHoldRef, initializeParameters(), landServiceCb(), odomCb(), posHoldServiceCb(), positionRefCb(), and takeoffServiceCb().
   : m_handlerState(nh, "mavros/state"), uav_reference::JoyControlInput(nh)
 {
   // Define Publishers
   _pubCarrotTrajectorySp =
     nh.advertise<trajectory_msgs::MultiDOFJointTrajectoryPoint>("carrot/trajectory", 1);
   _pubCarrotYawSp = nh.advertise<std_msgs::Float64>("carrot/yaw", 1);
   _pubUAVYaw = nh.advertise<std_msgs::Float64>("uav/yaw", 1);
   _pubCarrotPose = nh.advertise<geometry_msgs::PoseStamped>("carrot/pose", 1);
   _pubCarrotStatus = nh.advertise<std_msgs::String>("carrot/status", 1);
   // Define Subscribers
   _subOdom = nh.subscribe("odometry", 1, &uav_reference::CarrotReference::odomCb, this);
   _subPosHoldRef = nh.subscribe(
     "position_hold/trajectory", 1, &uav_reference::CarrotReference::positionRefCb, this);
   // Initialize position hold service
   _servicePoisitionHold = nh.advertiseService(
     "position_hold", &uav_reference::CarrotReference::posHoldServiceCb, this);
   _serviceTakeoff = nh.advertiseService(
     "takeoff", &uav_reference::CarrotReference::takeoffServiceCb, this);
   _serviceLand =
     nh.advertiseService("land", &uav_reference::CarrotReference::landServiceCb, this);
   _setModeToLandClient = nh.serviceClient<mavros_msgs::SetMode>("mavros/set_mode");
   _intResetClient = nh.serviceClient<std_srvs::Empty>("reset_integrator");
   initializeParameters();
   if (!_manualTakeoffEnabled) {
     ROS_WARN("CarrotReference - Automatic takeoff enabled, position hold disabled");
     _positionHold = false;
   }
   // Initialize references
   _carrotPoint.transforms = std::vector<geometry_msgs::Transform>(1);
   _carrotPoint.velocities = std::vector<geometry_msgs::Twist>(1);
   _carrotPoint.accelerations = std::vector<geometry_msgs::Twist>(1);
 }
uav_reference::CarrotReference::~CarrotReference () virtual
Definition at line 58 of file CarrotReference.cpp.
 {}
Member Function Documentation
void uav_reference::CarrotReference::initializeParameters () private
Initialize class parameters.
Definition at line 351 of file CarrotReference.cpp.
References _carrotEnabledIndex, _carrotEnabledValue, and _manualTakeoffEnabled.
Referenced by CarrotReference().
 {
   ROS_WARN("CarrotReference::initializeParameters()");
   ros::NodeHandle nhPrivate("~");
   bool initialized = nhPrivate.getParam("carrot_index", _carrotEnabledIndex)
                      && nhPrivate.getParam("carrot_enable", _carrotEnabledValue)
                      && nhPrivate.getParam("manual_takeoff", _manualTakeoffEnabled);
   ROS_INFO("CarrotReference::initializeParameters() - carrot button enable index is %d",
     _carrotEnabledIndex);
   ROS_INFO("CarrotReference::initializeParameters() - carrot enable value is %d",
     _carrotEnabledValue);
   ROS_WARN_COND(_manualTakeoffEnabled,
     "CarrotReference::initializeParameters() - manual takeoff enabled");
   ROS_WARN_COND(!_manualTakeoffEnabled,
     "CarrotReference::initializeParameters() - automatic takeoff enabled");
   if (!initialized) {
     ROS_FATAL(
       "CarrotReference::initializeParameters() -\
             Carrot enable index not properly initialized.");
     throw std::runtime_error("CarrotReference parameters not properly set.");
   }
 }
bool uav_reference::CarrotReference::isCarrotEnabled ()
True if carrot is enabled otherwise false.
Definition at line 432 of file CarrotReference.cpp.
References _carrotEnabled.
 { return _carrotEnabled; }
bool uav_reference::CarrotReference::isHoldEnabled ()
True if position hold is enabled, otherwise false.
Definition at line 434 of file CarrotReference.cpp.
References _positionHold.
 { return _positionHold; }
bool uav_reference::CarrotReference::landServiceCb (std_srvs::SetBool::Request & request, std_srvs::SetBool::Response & response) private
Definition at line 86 of file CarrotReference.cpp.
References _carrotEnabled, _carrotOnLand, _manualTakeoffEnabled, _positionHold, _setModeToLandClient, _takeoffHappened, ros_util::TopicHandler< T >::getData(), and m_handlerState.
Referenced by CarrotReference().
 {
   const auto set_response = [&response](bool success) { response.success = success; };
   if (_manualTakeoffEnabled) {
     ROS_FATAL("CarrotReference::landServiceCb - unable to land, in MANUAL_TAKEOFF.");
     set_response(false);
     return true;
   }
   if (m_handlerState.getData().mode != "GUIDED_NOGPS") {
     ROS_FATAL(
       "CarrotReference::landServiceCb - unable to land, not in GUIDED_NOGPS mode");
     set_response(false);
     return true;
   }
   if (!_carrotEnabled) {
     ROS_FATAL("CarrotReference::landServiceCb - unable to land, CARROT disabled");
     set_response(false);
     return true;
   }
   if (_carrotOnLand || !_takeoffHappened) {
     ROS_FATAL("CarrotReference::landServiceCb - unable to land, UAV on land");
     set_response(false);
     return true;
   }
   if (!request.data) {
     ROS_FATAL("CarrotReference::landServiceCb - request to not land recieved.");
     set_response(false);
     return true;
   }
   // Assume we want to land at this point
   mavros_msgs::SetMode::Request landMode_req;
   mavros_msgs::SetMode::Response landMode_resp;
   landMode_req.custom_mode = "LAND";
   if (!_setModeToLandClient.call(landMode_req, landMode_resp)) {
     ROS_FATAL("CarrotReference::landServiceCb - unable to set LAND mode");
     set_response(false);
     return true;
   }
   _positionHold = false;
   _carrotOnLand = true;
   ROS_INFO("Carrotreference::landServiceCb - LAND finished");
   set_response(true);
   return true;
 }
void uav_reference::CarrotReference::odomCb (const nav_msgs::OdometryConstPtr & msg) private
Odometry callback function. Used for extracting UAV yaw rotation.
Definition at line 263 of file CarrotReference.cpp.
References _firstPass, _pubUAVYaw, _uavPos, _uavYaw, util::calculateYaw(), and resetCarrot().
Referenced by CarrotReference().
 {
   double qx = msg->pose.pose.orientation.x;
   double qy = msg->pose.pose.orientation.y;
   double qz = msg->pose.pose.orientation.z;
   double qw = msg->pose.pose.orientation.w;
   // Extract UAV yaw
   _uavYaw = util::calculateYaw(qx, qy, qz, qw);
   // Publish UAV yaw message
   std_msgs::Float64 uavYawMsg;
   uavYawMsg.data = _uavYaw;
   _pubUAVYaw.publish(uavYawMsg);
   // Extract UAV position
   _uavPos[0] = msg->pose.pose.position.x;
   _uavPos[1] = msg->pose.pose.position.y;
   _uavPos[2] = msg->pose.pose.position.z;
   if (_firstPass) {
     _firstPass = false;
     resetCarrot();
   }
 }
bool uav_reference::CarrotReference::posHoldServiceCb (std_srvs::Empty::Request & request, std_srvs::Empty::Response & response) private
Position hold service callback.OS
Definition at line 60 of file CarrotReference.cpp.
References _carrotEnabled, _carrotOnLand, _positionHold, and resetCarrot().
Referenced by CarrotReference().
 {
   if (!_carrotEnabled) {
     ROS_FATAL(
       "CarrotReference::posHoldServiceCb - unable to activate POSITION_HOLD, carrot not "
       "enabled");
     return true;
   }
   if (_carrotOnLand) {
     ROS_FATAL(
       "CarrotReference::posHoldServiceCb - unable to activate POSITION_HOLD, carrot on "
       "land");
     return true;
   }
   if (!_positionHold) {
     ROS_WARN("CarrotReference::posHoldServiceCb - Position hold enabled");
     _positionHold = true;
     resetCarrot();
   }
   return true;
 }
void uav_reference::CarrotReference::positionRefCb (const trajectory_msgs::MultiDOFJointTrajectoryPointConstPtr & posMsg) private
Callback function for Position reference. Works only during position hold mode.
Definition at line 194 of file CarrotReference.cpp.
References _carrotPoint, _carrotYaw, _positionHold, and util::calculateYaw().
Referenced by CarrotReference().
 {
   if (_positionHold) {
     _carrotPoint = *posMsg;
     _carrotYaw = util::calculateYaw(posMsg->transforms[0].rotation.x,
       posMsg->transforms[0].rotation.y,
       posMsg->transforms[0].rotation.z,
       posMsg->transforms[0].rotation.w);
     ROS_WARN_THROTTLE(5.0, "CarrotReference - Trajectory reference received");
   } else {
     ROS_FATAL(
       "CarrotReference - Trajectory reference recieved, but position hold mode is "
       "disabled.");
   }
 }
void uav_reference::CarrotReference::publishCarrotSetpoint ()
Publish carrot position setpoint as a Vector3 ROS message.
Definition at line 325 of file CarrotReference.cpp.
References _carrotPoint, _carrotYaw, _pubCarrotPose, _pubCarrotTrajectorySp, and _pubCarrotYawSp.
Referenced by uav_reference::runDefault().
 {
   tf2::Quaternion q;
   q.setEulerZYX(_carrotYaw, 0, 0);
   // Publish PoseStamped carrot reference
   _pubCarrotTrajectorySp.publish(_carrotPoint);
   geometry_msgs::PoseStamped pose;
   pose.header.frame_id = "world";
   pose.header.stamp = ros::Time::now();
   pose.pose.position.x = _carrotPoint.transforms[0].translation.x;
   pose.pose.position.y = _carrotPoint.transforms[0].translation.y;
   pose.pose.position.z = _carrotPoint.transforms[0].translation.z;
   pose.pose.orientation.x = q.getX();
   pose.pose.orientation.y = q.getY();
   pose.pose.orientation.z = q.getZ();
   pose.pose.orientation.w = q.getW();
   _pubCarrotPose.publish(pose);
   // Publish referent yaw message
   std_msgs::Float64 yawRefMsg;
   yawRefMsg.data = _carrotYaw;
   _pubCarrotYawSp.publish(yawRefMsg);
 }
void uav_reference::CarrotReference::resetCarrot () private
Reset carrot trajectory point.
Definition at line 243 of file CarrotReference.cpp.
References _carrotPoint, _carrotYaw, _uavPos, and _uavYaw.
Referenced by odomCb(), posHoldServiceCb(), takeoffServiceCb(), updateCarrot(), and updateCarrotStatus().
 {
   _carrotPoint.transforms = std::vector<geometry_msgs::Transform>(1);
   _carrotPoint.velocities = std::vector<geometry_msgs::Twist>(1);
   _carrotPoint.accelerations = std::vector<geometry_msgs::Twist>(1);
   _carrotPoint.transforms[0].translation.x = _uavPos[0];
   _carrotPoint.transforms[0].translation.y = _uavPos[1];
   _carrotPoint.transforms[0].translation.z = _uavPos[2];
   // Set carrot orientation
   _carrotYaw = _uavYaw;
   tf2::Quaternion q;
   q.setEulerZYX(_carrotYaw, 0, 0);
   _carrotPoint.transforms[0].rotation.x = q.getX();
   _carrotPoint.transforms[0].rotation.y = q.getY();
   _carrotPoint.transforms[0].rotation.z = q.getZ();
   _carrotPoint.transforms[0].rotation.w = q.getW();
 }
void uav_reference::CarrotReference::resetIntegrators () private
Definition at line 211 of file CarrotReference.cpp.
References _intResetClient.
Referenced by updateCarrotStatus().
 {
   std_srvs::Empty::Request req;
   std_srvs::Empty::Response resp;
   if (!_intResetClient.call(req, resp)) {
     ROS_FATAL("CarrotReference - Unable to reset integrators");
     return;
   }
   ROS_INFO("Controller integrators reset.");
 }
bool uav_reference::CarrotReference::takeoffServiceCb (uav_ros_control_msgs::TakeOff::Request & request, uav_ros_control_msgs::TakeOff::Response & response) private
Definition at line 140 of file CarrotReference.cpp.
References _carrotEnabled, _carrotOnLand, _carrotPoint, _manualTakeoffEnabled, _positionHold, _takeoffHappened, _uavPos, ros_util::TopicHandler< T >::getData(), m_handlerState, and resetCarrot().
Referenced by CarrotReference().
 {
   const auto set_response = [&response](bool success) {
     response.success = success;
     if (success) {
       response.message = "Takeoff sucessful";
     } else {
       response.message = "Takeoff unsucessful";
     }
   };
   if (_manualTakeoffEnabled) {
     ROS_FATAL("CarrotReference::takeoffServiceCb - unable to takeoff, in MANUAL_TAKEOFF");
     set_response(false);
     return true;
   }
   // Check if the UAV is armed
   if (!m_handlerState.getData().armed) {
     ROS_FATAL("CarrotReference::takeoffServiceCb - unable to takeoff, not ARMED.");
     set_response(false);
     return true;
   }
   // Check if carrot is enabled
   if (!_carrotEnabled) {
     ROS_FATAL(
       "CarrotReference::takeoffServiceCb - unable to takeoff, carrot not enabled");
     set_response(false);
     return true;
   }
   if (!_carrotOnLand) {
     ROS_FATAL(
       "CarrotReference::takeoffServiceCb - unable to takeoff, not in CARROT_ON_LAND "
       "mode");
     set_response(false);
     return true;
   }
   resetCarrot();
   _carrotPoint.transforms[0].translation.z = _uavPos[2] + request.rel_alt;
   _positionHold = true;
   _takeoffHappened = true;
   _carrotOnLand = false;
   ROS_INFO("CarrotReference::takeoffServiceCb - enable position hold");
   set_response(true);
   return true;
 }
void uav_reference::CarrotReference::updateCarrot ()
Update carrot position setpoint, with default joystick offset values. Also update the yaw reference value.
Definition at line 223 of file CarrotReference.cpp.
References _carrotEnabled, _carrotOnLand, _positionHold, uav_reference::JoyControlInput::isJoyActive(), resetCarrot(), updateCarrotXY(), updateCarrotYaw(), and updateCarrotZ().
Referenced by uav_reference::runDefault().
 {
   // Disable Position hold if carrot inputs exist
   if (_positionHold && isJoyActive()) {
     ROS_WARN("Position hold disabled - resetting carrot position");
     resetCarrot();
     _positionHold = false;
   }
   // Update carrot unless in position hold
   if (!_positionHold && _carrotEnabled && !_carrotOnLand) {
     updateCarrotXY();
     updateCarrotZ();
     updateCarrotYaw();
   } else if (!_positionHold && !_carrotEnabled) {
     // Map odometry to carrot
     resetCarrot();
   }
 }
void uav_reference::CarrotReference::updateCarrotStatus ()
Check if carrot mode is entered. This method will reset carrot position when entering carrot reference mode for the first time.
Definition at line 378 of file CarrotReference.cpp.
References _carrotEnabled, _carrotEnabledIndex, _carrotEnabledValue, _carrotOnLand, _manualTakeoffEnabled, _positionHold, _pubCarrotStatus, _takeoffHappened, CARROT_OFF, CARROT_ON_AIR, CARROT_ON_LAND, ros_util::TopicHandler< T >::getData(), uav_reference::JoyControlInput::getJoyButtons(), m_handlerState, POS_HOLD, resetCarrot(), and resetIntegrators().
Referenced by uav_reference::runDefault().
 {
   // Check if we landed after takeoff happened in automatic takeoff mode
   if (!_manualTakeoffEnabled && _takeoffHappened && !m_handlerState.getData().armed) {
     ROS_WARN("CarrotReference::updateCarrotStatus - UAV disarmed, assume LAND happened");
     _takeoffHappened = false;
     if (_carrotEnabled) { _carrotOnLand = true; }
     resetCarrot();
   }
   // Detect enable button - rising edge
   if (getJoyButtons()[_carrotEnabledIndex] == _carrotEnabledValue && !_carrotEnabled) {
     if (_manualTakeoffEnabled || _takeoffHappened) {
       _carrotEnabled = true;
       _carrotOnLand = false;
       ROS_INFO("CarrotReference::updateCarrotStatus - CARROT_ON_AIR enabled.");
       resetIntegrators();
       resetCarrot();
     } else if (!_carrotOnLand) {
       ROS_INFO("CarrotReference::updateCarrotStatus - CARROT_ON_LAND enabled.");
       _carrotEnabled = true;
       _carrotOnLand = true;
       resetIntegrators();
       resetCarrot();
     }
   }
   // Detect enable button - falling edge
   if (getJoyButtons()[_carrotEnabledIndex] == (1 - _carrotEnabledValue)
       && _carrotEnabled) {
     _carrotEnabled = false;
     _positionHold = false;
     _carrotOnLand = false;
     resetIntegrators();
     ROS_INFO("CarrotRefernce::updateCarrotStatus - carrot disabled.\n");
   }
   // Publish carrot status.
   std_msgs::String status;
   if (_positionHold && _carrotEnabled) {
     status.data = POS_HOLD;
   } else if (!_positionHold && _carrotEnabled) {
     if (_carrotOnLand) {
       status.data = CARROT_ON_LAND;
     } else {
       status.data = CARROT_ON_AIR;
     }
   } else {
     status.data = CARROT_OFF;
   }
   _pubCarrotStatus.publish(status);
 }
void uav_reference::CarrotReference::updateCarrotXY (double x, double y) private
Update x and y component of carrot position setpoint with the given value.
Parameters
- x carrot offset
- y carrot offset
Definition at line 313 of file CarrotReference.cpp.
References _carrotPoint, and _uavYaw.
 {
   // Adjust carrot position w.r.t. the global coordinate system
   _carrotPoint.transforms[0].translation.x += cos(-_uavYaw) * xOff + sin(-_uavYaw) * yOff;
   _carrotPoint.transforms[0].translation.y += cos(-_uavYaw) * yOff - sin(-_uavYaw) * xOff;
 }
void uav_reference::CarrotReference::updateCarrotXY () private
Update x component of carrot position setpoint with default joystick offset value.
Definition at line 303 of file CarrotReference.cpp.
References uav_reference::JoyControlInput::getXOffsetManual(), and uav_reference::JoyControlInput::getYOffsetManual().
Referenced by updateCarrot().
 {
   updateCarrotXY(getXOffsetManual(), getYOffsetManual());
 }
void uav_reference::CarrotReference::updateCarrotYaw () private
Update carrot Yaw component
Definition at line 289 of file CarrotReference.cpp.
References _carrotPoint, _carrotYaw, uav_reference::JoyControlInput::getYawSpManual(), and util::wrapMinMax().
Referenced by updateCarrot().
 {
   // Update Carrot yaw angle and wrap to PI
   _carrotYaw += getYawSpManual();
   _carrotYaw = util::wrapMinMax(_carrotYaw, -M_PI, M_PI);
   tf2::Quaternion q;
   q.setEulerZYX(_carrotYaw, 0, 0);
   _carrotPoint.transforms[0].rotation.x = q.getX();
   _carrotPoint.transforms[0].rotation.y = q.getY();
   _carrotPoint.transforms[0].rotation.z = q.getZ();
   _carrotPoint.transforms[0].rotation.w = q.getW();
 }
void uav_reference::CarrotReference::updateCarrotZ (double z) private
Update z component of carrot position setpoint with the given value.
Parameters
- z carrot offset
Definition at line 320 of file CarrotReference.cpp.
References _carrotPoint.
 {
   _carrotPoint.transforms[0].translation.z += zOff;
 }
void uav_reference::CarrotReference::updateCarrotZ () private
Update z component of carrot position setpoint with default joystick offset value.
Definition at line 308 of file CarrotReference.cpp.
References uav_reference::JoyControlInput::getZOffsetManual().
Referenced by updateCarrot().
 {
   updateCarrotZ(getZOffsetManual());
 }
Field Documentation
bool uav_reference::CarrotReference::_carrotEnabled = false private
True if carrot mode is enabled otherwise false
Definition at line 137 of file CarrotReference.hpp.
Referenced by isCarrotEnabled(), landServiceCb(), posHoldServiceCb(), takeoffServiceCb(), updateCarrot(), and updateCarrotStatus().
int uav_reference::CarrotReference::_carrotEnabledIndex = -1 private
Index used for enabling carrot mode
Definition at line 143 of file CarrotReference.hpp.
Referenced by initializeParameters(), and updateCarrotStatus().
int uav_reference::CarrotReference::_carrotEnabledValue = 1 private
Carrot enable button value, 0 or 1
Definition at line 146 of file CarrotReference.hpp.
Referenced by initializeParameters(), and updateCarrotStatus().
bool uav_reference::CarrotReference::_carrotOnLand = false private
Definition at line 151 of file CarrotReference.hpp.
Referenced by landServiceCb(), posHoldServiceCb(), takeoffServiceCb(), updateCarrot(), and updateCarrotStatus().
trajectory_msgs::MultiDOFJointTrajectoryPoint uav_reference::CarrotReference::_carrotPoint private
Carrot reference used for position hold.
Definition at line 125 of file CarrotReference.hpp.
Referenced by CarrotReference(), positionRefCb(), publishCarrotSetpoint(), resetCarrot(), takeoffServiceCb(), updateCarrotXY(), updateCarrotYaw(), and updateCarrotZ().
double uav_reference::CarrotReference::_carrotYaw = 0 private
Referent yaw angle.
Definition at line 131 of file CarrotReference.hpp.
Referenced by positionRefCb(), publishCarrotSetpoint(), resetCarrot(), and updateCarrotYaw().
bool uav_reference::CarrotReference::_firstPass = true private
Definition at line 149 of file CarrotReference.hpp.
Referenced by odomCb().
ros::ServiceClient uav_reference::CarrotReference::_intResetClient private
Definition at line 169 of file CarrotReference.hpp.
Referenced by CarrotReference(), and resetIntegrators().
bool uav_reference::CarrotReference::_manualTakeoffEnabled = true private
Definition at line 150 of file CarrotReference.hpp.
Referenced by CarrotReference(), initializeParameters(), landServiceCb(), takeoffServiceCb(), and updateCarrotStatus().
bool uav_reference::CarrotReference::_positionHold = true private
True if position hold mode is enabled, otherwise false
Definition at line 140 of file CarrotReference.hpp.
Referenced by CarrotReference(), isHoldEnabled(), landServiceCb(), posHoldServiceCb(), positionRefCb(), takeoffServiceCb(), updateCarrot(), and updateCarrotStatus().
ros::Publisher uav_reference::CarrotReference::_pubCarrotPose private
Definition at line 157 of file CarrotReference.hpp.
Referenced by CarrotReference(), and publishCarrotSetpoint().
ros::Publisher uav_reference::CarrotReference::_pubCarrotStatus private
Definition at line 158 of file CarrotReference.hpp.
Referenced by CarrotReference(), and updateCarrotStatus().
ros::Publisher uav_reference::CarrotReference::_pubCarrotTrajectorySp private
Define all Publishers
Definition at line 154 of file CarrotReference.hpp.
Referenced by CarrotReference(), and publishCarrotSetpoint().
ros::Publisher uav_reference::CarrotReference::_pubCarrotYawSp private
Definition at line 155 of file CarrotReference.hpp.
Referenced by CarrotReference(), and publishCarrotSetpoint().
ros::Publisher uav_reference::CarrotReference::_pubUAVYaw private
Definition at line 156 of file CarrotReference.hpp.
Referenced by CarrotReference(), and odomCb().
ros::ServiceServer uav_reference::CarrotReference::_serviceLand private
Definition at line 166 of file CarrotReference.hpp.
Referenced by CarrotReference().
ros::ServiceServer uav_reference::CarrotReference::_servicePoisitionHold private
Define all the services
Definition at line 166 of file CarrotReference.hpp.
Referenced by CarrotReference().
ros::ServiceServer uav_reference::CarrotReference::_serviceTakeoff private
Definition at line 166 of file CarrotReference.hpp.
Referenced by CarrotReference().
ros::ServiceClient uav_reference::CarrotReference::_setModeToLandClient private
Definition at line 169 of file CarrotReference.hpp.
Referenced by CarrotReference(), and landServiceCb().
ros::Subscriber uav_reference::CarrotReference::_subOdom private
Define all Subscribers.
Definition at line 161 of file CarrotReference.hpp.
Referenced by CarrotReference().
ros::Subscriber uav_reference::CarrotReference::_subPosHoldRef private
Definition at line 162 of file CarrotReference.hpp.
Referenced by CarrotReference().
bool uav_reference::CarrotReference::_takeoffHappened = false private
Definition at line 151 of file CarrotReference.hpp.
Referenced by landServiceCb(), takeoffServiceCb(), and updateCarrotStatus().
std::array<double, 3> uav_reference::CarrotReference::_uavPos { 0.0, 0.0, 0.0 } private
UAV current position array.
Definition at line 128 of file CarrotReference.hpp.
Referenced by odomCb(), resetCarrot(), and takeoffServiceCb().
double uav_reference::CarrotReference::_uavYaw = 0 private
Current UAV yaw angle
Definition at line 134 of file CarrotReference.hpp.
Referenced by odomCb(), resetCarrot(), and updateCarrotXY().
ros_util::TopicHandler<mavros_msgs::State> uav_reference::CarrotReference::m_handlerState private
Definition at line 163 of file CarrotReference.hpp.
Referenced by landServiceCb(), takeoffServiceCb(), and updateCarrotStatus().
The documentation for this class was generated from the following files:
uav_ros_control/include/uav_ros_control/reference/CarrotReference.hpp
uav_ros_control/src/reference/CarrotReference.cpp