uav_ros_control: point2trajectory.TrajectoryPacker Class Reference
point2trajectory.TrajectoryPacker Class Reference
Public Member Functions
def __init__ (self)
def ref_sub (self, msg)
def status_cb (self, msg)
def odom_sub (self, msg)
Data Fields
odom_msg
pub_odom
old_odom
status
traj_pub
Detailed Description
Packs a single trajectory point into a trajectory message.
Definition at line 10 of file point2trajectory.py.
Constructor & Destructor Documentation
def point2trajectory.TrajectoryPacker.__init__ (self)
Definition at line 15 of file point2trajectory.py.
References point2trajectory.TrajectoryPacker.odom_sub(), and point2trajectory.TrajectoryPacker.ref_sub().
     def __init__(self):
         rospy.Subscriber('trajectory_point', MultiDOFJointTrajectoryPoint, self.ref_sub)
         rospy.Subscriber('odometry', Odometry, self.odom_sub)
         self.odom_msg = Odometry()
         rospy.Subscriber('carrot/status', String, self.status_cb)
         self.pub_odom = True
         self.old_odom = Odometry()
         self.status = "OFF"
         self.traj_pub = rospy.Publisher('trajectory', MultiDOFJointTrajectory, queue_size=1)
Member Function Documentation
def point2trajectory.TrajectoryPacker.odom_sub (self, msg)
Definition at line 51 of file point2trajectory.py.
References point2trajectory.TrajectoryPacker.odom_msg.
Referenced by point2trajectory.TrajectoryPacker.__init__().
     def odom_sub(self, msg):
         self.odom_msg = msg
def point2trajectory.TrajectoryPacker.ref_sub (self, msg)
Definition at line 25 of file point2trajectory.py.
References point2trajectory.TrajectoryPacker.status.
Referenced by point2trajectory.TrajectoryPacker.__init__().
     def ref_sub(self, msg):
         traj = MultiDOFJointTrajectory()
         traj.points = []
         traj.points.append(msg)
         if not self.status == "OFF":
             self.traj_pub.publish(traj)
def point2trajectory.TrajectoryPacker.status_cb (self, msg)
Definition at line 32 of file point2trajectory.py.
References point2trajectory.TrajectoryPacker.status.
     def status_cb(self, msg):
         self.status = msg.data
         if msg.data == "OFF":
             traj = MultiDOFJointTrajectory()
             traj.points = []
             # Take it from odometry
             point = MultiDOFJointTrajectoryPoint()
             transform = Transform()
             transform.translation.x = self.odom_msg.pose.pose.position.x
             transform.translation.y = self.odom_msg.pose.pose.position.y
             transform.translation.z = self.odom_msg.pose.pose.position.z
             transform.rotation.x = self.odom_msg.pose.pose.orientation.x
             transform.rotation.y = self.odom_msg.pose.pose.orientation.y
             transform.rotation.z = self.odom_msg.pose.pose.orientation.z
             transform.rotation.w = self.odom_msg.pose.pose.orientation.w
             point.transforms.append(transform)
             traj.points.append(point)
         self.traj_pub.publish(traj)
Field Documentation
point2trajectory.TrajectoryPacker.odom_msg
Definition at line 18 of file point2trajectory.py.
Referenced by point2trajectory.TrajectoryPacker.odom_sub().
point2trajectory.TrajectoryPacker.old_odom
Definition at line 21 of file point2trajectory.py.
point2trajectory.TrajectoryPacker.pub_odom
Definition at line 20 of file point2trajectory.py.
point2trajectory.TrajectoryPacker.status
Definition at line 22 of file point2trajectory.py.
Referenced by point2trajectory.TrajectoryPacker.ref_sub(), and point2trajectory.TrajectoryPacker.status_cb().
point2trajectory.TrajectoryPacker.traj_pub
Definition at line 23 of file point2trajectory.py.
The documentation for this class was generated from the following file:
uav_ros_control/scripts/point2trajectory.py