uav_ros_control: ros_util::TopicHandlerWithFunction< T > Class Template Reference
ros_util::TopicHandlerWithFunction< T > Class Template Reference
#include <Util.hpp>
Public Member Functions
TopicHandlerWithFunction (ros::NodeHandle &t_nh, const std::string &t_topicName, std::function< void(const T &)> t_postCallbackFunction, const double t_timeoutDuration=2)
const T & getData ()
bool isResponsive ()
bool isMessageRecieved ()
Private Member Functions
void callback (const T &msg)
void watchdog_callback (const ros::TimerEvent &e)
Private Attributes
ros::Timer m_watchdogTimer
double m_topicTimeout
double m_lastMessgeTime
bool m_isResponsive
bool m_messageRecieved
std::function< void(const T &)> m_postCallbackFunction
ros::Subscriber m_subT
T m_data
const std::string m_topicName
Detailed Description
template<class T>
class ros_util::TopicHandlerWithFunction< T >
Definition at line 98 of file Util.hpp.
Constructor & Destructor Documentation
template<class T > ros_util::TopicHandlerWithFunction< T >::TopicHandlerWithFunction (ros::NodeHandle & t_nh, const std::string & t_topicName, std::function< void(const T &)> t_postCallbackFunction, const double t_timeoutDuration = 2) inline
Definition at line 101 of file Util.hpp.
References ros_util::TopicHandlerWithFunction< T >::callback(), and ros_util::TopicHandlerWithFunction< T >::watchdog_callback().
     : m_topicName(t_topicName), m_topicTimeout(t_timeoutDuration), m_lastMessgeTime(0),
       m_isResponsive(false), m_postCallbackFunction(t_postCallbackFunction),
       m_messageRecieved(false)
   {
     m_subT = t_nh.subscribe(m_topicName, 1, &TopicHandlerWithFunction::callback, this);
     if (t_timeoutDuration > 0) {
       m_watchdogTimer = t_nh.createTimer(ros::Duration(t_timeoutDuration),
         &TopicHandlerWithFunction::watchdog_callback,
         this);
     }
   }
Member Function Documentation
template<class T > void ros_util::TopicHandlerWithFunction< T >::callback (const T & msg) inline private
Definition at line 126 of file Util.hpp.
Referenced by ros_util::TopicHandlerWithFunction< T >::TopicHandlerWithFunction().
   {
     m_data = std::move(msg);
     m_lastMessgeTime = ros::Time::now().toSec();
     m_messageRecieved = true;
     m_postCallbackFunction(m_data);
   }
template<class T > const T& ros_util::TopicHandlerWithFunction< T >::getData () inline
Definition at line 118 of file Util.hpp.
 { return m_data; }
template<class T > bool ros_util::TopicHandlerWithFunction< T >::isMessageRecieved () inline
Definition at line 123 of file Util.hpp.
 { return m_messageRecieved; }
template<class T > bool ros_util::TopicHandlerWithFunction< T >::isResponsive () inline
Definition at line 121 of file Util.hpp.
 { return m_isResponsive; }
template<class T > void ros_util::TopicHandlerWithFunction< T >::watchdog_callback (const ros::TimerEvent & e) inline private
Definition at line 134 of file Util.hpp.
Referenced by ros_util::TopicHandlerWithFunction< T >::TopicHandlerWithFunction().
   {
     double elapsedTime = ros::Time::now().toSec() - m_lastMessgeTime;
     if (elapsedTime > m_topicTimeout) {
       m_isResponsive = false;
       ROS_FATAL_STREAM("Topic: [" << m_topicName << "] unresponsive.");
     } else {
       m_isResponsive = true;
     }
   }
Field Documentation
template<class T > T ros_util::TopicHandlerWithFunction< T >::m_data private
Definition at line 151 of file Util.hpp.
template<class T > bool ros_util::TopicHandlerWithFunction< T >::m_isResponsive private
Definition at line 147 of file Util.hpp.
template<class T > double ros_util::TopicHandlerWithFunction< T >::m_lastMessgeTime private
Definition at line 146 of file Util.hpp.
template<class T > bool ros_util::TopicHandlerWithFunction< T >::m_messageRecieved private
Definition at line 147 of file Util.hpp.
template<class T > std::function<void(const T &)> ros_util::TopicHandlerWithFunction< T >::m_postCallbackFunction private
Definition at line 149 of file Util.hpp.
template<class T > ros::Subscriber ros_util::TopicHandlerWithFunction< T >::m_subT private
Definition at line 150 of file Util.hpp.
template<class T > const std::string ros_util::TopicHandlerWithFunction< T >::m_topicName private
Definition at line 152 of file Util.hpp.
template<class T > double ros_util::TopicHandlerWithFunction< T >::m_topicTimeout private
Definition at line 146 of file Util.hpp.
template<class T > ros::Timer ros_util::TopicHandlerWithFunction< T >::m_watchdogTimer private
Definition at line 145 of file Util.hpp.
The documentation for this class was generated from the following file:
uav_ros_control/include/uav_ros_control/filters/Util.hpp