uav_ros_control: uav_controller::ControlBase Class Reference
uav_controller::ControlBase Class Reference
#include <ControlBase.hpp>
Public Member Functions
ControlBase (ros::NodeHandle &nh)
virtual ~ControlBase ()=default
void setAttitudeSp (double roll, double pitch, double yaw)
void setThrustSp (double thrust)
const std::array< double, 3 > & getCurrPosition ()
const std::array< double, 3 > & getCurrVelocity ()
double getCurrentYaw ()
void publishAttitudeTarget (int typeMask, double yawRate=0)
void publishEulerSp ()
const trajectory_msgs::MultiDOFJointTrajectoryPoint & getCurrentReference ()
void overridePitchTarget (double newPitch)
void overrideRollTarget (double newRoll)
void overrideYawTarget (double newYaw)
Private Member Functions
void odomCb (const nav_msgs::OdometryConstPtr &)
void msfOdomCb (const nav_msgs::OdometryConstPtr &)
void trajPointCb (const trajectory_msgs::MultiDOFJointTrajectoryPointConstPtr &)
Private Attributes
double _currentYaw = 0
std::array< double, 3 > _currentPosition { 0.0, 0.0, 0.0 }
std::array< double, 3 > _currentVelocity { 0.0, 0.0, 0.0 }
std::array< double, 4 > _attThrustSp { 0.0, 0.0, 0.0, 0.0 }
trajectory_msgs::MultiDOFJointTrajectoryPoint _currentReference
ros::Subscriber _subOdom
ros::Subscriber _subReference
ros::Publisher _pubEulerSetpoint
ros::Publisher _pubAttitudeSetpoint
Detailed Description
This class is used for defining UAV odometry subscribers. It will also define attitude an thrust setpoint publisher.
This class is meant to be used as a base class for some other control strategy.
Definition at line 29 of file ControlBase.hpp.
Constructor & Destructor Documentation
uav_controller::ControlBase::ControlBase (ros::NodeHandle & nh) explicit
Default constructor. Used for reading ROS parameters and initalizing private variables.
Parameters
nh - ROS node handle, used for initializing subscribers and publishers
Definition at line 24 of file ControlBase.cpp.
References _currentReference, _pubAttitudeSetpoint, _pubEulerSetpoint, _subOdom, _subReference, msfOdomCb(), odomCb(), and trajPointCb().
 {
   ros::NodeHandle nhPrivate("~");
   bool msf_callback = false;
   bool initialized = nhPrivate.getParam("msf_callback", msf_callback);
   if (!initialized) {
     ROS_FATAL("ControlBase - parameters not loaded.");
     throw std::runtime_error("Parameters not loaded");
   }
   auto odomCallback = &uav_controller::ControlBase::odomCb;
   if (msf_callback) {
     odomCallback = &uav_controller::ControlBase::msfOdomCb;
   }
   // Initialize all subscribers
   _subOdom = nh.subscribe("odometry", 1, odomCallback, this);
   _subReference = nh.subscribe(
     "uav/trajectory_point", 1, &uav_controller::ControlBase::trajPointCb, this);
   // Initialized all publishers
   _pubAttitudeSetpoint =
     nh.advertise<mavros_msgs::AttitudeTarget>("uav/attitude_target", 1);
   _pubEulerSetpoint = nh.advertise<geometry_msgs::Vector3>("uav/euler_setpoint", 1);
   // Initialize references
   _currentReference.transforms = std::vector<geometry_msgs::Transform>(1);
   _currentReference.velocities = std::vector<geometry_msgs::Twist>(1);
   _currentReference.accelerations = std::vector<geometry_msgs::Twist>(1);
 }
virtual uav_controller::ControlBase::~ControlBase () virtual default
Member Function Documentation
const trajectory_msgs::MultiDOFJointTrajectoryPoint & uav_controller::ControlBase::getCurrentReference ()
Get trajectory point reference.
Definition at line 167 of file ControlBase.cpp.
References _currentReference.
Referenced by uav_controller::CascadePID::calculateAttThrustSp().
 {
   return _currentReference;
 }
double uav_controller::ControlBase::getCurrentYaw ()
Return current UAV yaw angle.
Definition at line 172 of file ControlBase.cpp.
References _currentYaw.
Referenced by uav_controller::CascadePID::calculateAttThrustSp(), and dist_control::DistanceControl::doDistanceControl().
 { return _currentYaw; }
const std::array< double, 3 > & uav_controller::ControlBase::getCurrPosition ()
Returns constant reference to the current position.
Definition at line 101 of file ControlBase.cpp.
References _currentPosition.
Referenced by uav_controller::CascadePID::calculateAttThrustSp().
 {
   return _currentPosition;
 }
const std::array< double, 3 > & uav_controller::ControlBase::getCurrVelocity ()
Returns constant reference to the current velocity.
Definition at line 106 of file ControlBase.cpp.
References _currentVelocity.
Referenced by uav_controller::CascadePID::calculateAttThrustSp().
 {
   return _currentVelocity;
 }
void uav_controller::ControlBase::msfOdomCb (const nav_msgs::OdometryConstPtr & message) private
MSF odometry callback function
Definition at line 70 of file ControlBase.cpp.
References _currentPosition, _currentVelocity, _currentYaw, and util::calculateYaw().
Referenced by ControlBase().
 {
   _currentPosition[0] = message->pose.pose.position.x;
   _currentPosition[1] = message->pose.pose.position.y;
   _currentPosition[2] = message->pose.pose.position.z;
   _currentVelocity[0] = cos(-_currentYaw) * message->twist.twist.linear.x
                         + sin(-_currentYaw) * message->twist.twist.linear.y;
   _currentVelocity[1] = cos(-_currentYaw) * message->twist.twist.linear.y
                         - sin(-_currentYaw) * message->twist.twist.linear.x;
   _currentVelocity[2] = message->twist.twist.linear.z;
   _currentYaw = util::calculateYaw(message->pose.pose.orientation.x,
     message->pose.pose.orientation.y,
     message->pose.pose.orientation.z,
     message->pose.pose.orientation.w);
 }
void uav_controller::ControlBase::odomCb (const nav_msgs::OdometryConstPtr & message) private
Odometry callback function.
Definition at line 54 of file ControlBase.cpp.
References _currentPosition, _currentVelocity, _currentYaw, and util::calculateYaw().
Referenced by ControlBase().
 {
   _currentPosition[0] = message->pose.pose.position.x;
   _currentPosition[1] = message->pose.pose.position.y;
   _currentPosition[2] = message->pose.pose.position.z;
   _currentVelocity[0] = message->twist.twist.linear.x;
   _currentVelocity[1] = message->twist.twist.linear.y;
   _currentVelocity[2] = -message->twist.twist.linear.z;
   _currentYaw = util::calculateYaw(message->pose.pose.orientation.x,
     message->pose.pose.orientation.y,
     message->pose.pose.orientation.z,
     message->pose.pose.orientation.w);
 }
void uav_controller::ControlBase::overridePitchTarget (double newPitch)
Definition at line 147 of file ControlBase.cpp.
References _attThrustSp.
Referenced by dist_control::DistanceControl::doDistanceControl().
 {
   _attThrustSp[1] = pitch;
 }
void uav_controller::ControlBase::overrideRollTarget (double newRoll)
Definition at line 142 of file ControlBase.cpp.
References _attThrustSp.
 {
   _attThrustSp[0] = roll;
 }
void uav_controller::ControlBase::overrideYawTarget (double newYaw)
Definition at line 152 of file ControlBase.cpp.
References _attThrustSp.
Referenced by dist_control::DistanceControl::doDistanceControl().
 {
   _attThrustSp[2] = yaw;
 }
void uav_controller::ControlBase::publishAttitudeTarget (int typeMask, double yawRate = 0)
Publish attitude setpoiint.
- AttitudeTarget bitmask - Alse set yawRate if bitmask enables it
Definition at line 111 of file ControlBase.cpp.
References _attThrustSp, and _pubAttitudeSetpoint.
Referenced by uav_controller::runDefault(), and dist_control::runDefault().
 {
   tf2::Quaternion q;
   q.setRPY(_attThrustSp[0], _attThrustSp[1], _attThrustSp[2]);
   mavros_msgs::AttitudeTarget newMessage;
   newMessage.header.stamp = ros::Time::now();
   newMessage.type_mask = typeMask;
   newMessage.body_rate.z = yawRate;
   newMessage.orientation.x = q.getX();
   newMessage.orientation.y = q.getY();
   newMessage.orientation.z = q.getZ();
   newMessage.orientation.w = q.getW();
   newMessage.thrust = _attThrustSp[3];
   _pubAttitudeSetpoint.publish(newMessage);
 }
void uav_controller::ControlBase::publishEulerSp ()
Publish setpoint euler angles as a Vector3 ROS message.
Definition at line 157 of file ControlBase.cpp.
References _attThrustSp, and _pubEulerSetpoint.
Referenced by uav_controller::runDefault(), and dist_control::runDefault().
 {
   geometry_msgs::Vector3 newMessage;
   newMessage.x = _attThrustSp[0];
   newMessage.y = _attThrustSp[1];
   newMessage.z = _attThrustSp[2];
   _pubEulerSetpoint.publish(newMessage);
 }
void uav_controller::ControlBase::setAttitudeSp (double roll, double pitch, double yaw)
Set roll, pitch, yaw attitude setpoint.
Parameters
roll - Roll angle setpoint
pitch - Pitch angle setpoint
yaw - Yaw angle setpoint
Definition at line 133 of file ControlBase.cpp.
References _attThrustSp.
Referenced by uav_controller::CascadePID::calculateAttThrustSp().
 {
   _attThrustSp[0] = roll;
   _attThrustSp[1] = pitch;
   _attThrustSp[2] = yaw;
 }
void uav_controller::ControlBase::setThrustSp (double thrust)
Set thrust setpoint.
Parameters
thrust - New thrust setpoint
Definition at line 128 of file ControlBase.cpp.
References _attThrustSp.
Referenced by uav_controller::CascadePID::calculateAttThrustSp().
 {
   _attThrustSp[3] = thrust;
 }
void uav_controller::ControlBase::trajPointCb (const trajectory_msgs::MultiDOFJointTrajectoryPointConstPtr & msg) private
Trajectory point callback function.
Definition at line 88 of file ControlBase.cpp.
References _currentReference.
Referenced by ControlBase().
 {
   if (msg->transforms.empty() || msg->velocities.empty() || msg->accelerations.empty()) {
     ROS_FATAL("ControlBase::trajPointCb - Trajectory point incomplete.");
     return;
   }
   _currentReference.transforms[0] = msg->transforms[0];
   _currentReference.velocities[0] = msg->velocities[0];
   _currentReference.accelerations[0] = msg->accelerations[0];
 }
Field Documentation
std::array<double, 4> uav_controller::ControlBase::_attThrustSp { 0.0, 0.0, 0.0, 0.0 } private
Attitude setpoint array. Attitude is considered in RPY. Thrust is in [0, 1] range.
Definition at line 122 of file ControlBase.hpp.
Referenced by overridePitchTarget(), overrideRollTarget(), overrideYawTarget(), publishAttitudeTarget(), publishEulerSp(), setAttitudeSp(), and setThrustSp().
std::array<double, 3> uav_controller::ControlBase::_currentPosition { 0.0, 0.0, 0.0 } private
Current local position vector.
Definition at line 115 of file ControlBase.hpp.
Referenced by getCurrPosition(), msfOdomCb(), and odomCb().
trajectory_msgs::MultiDOFJointTrajectoryPoint uav_controller::ControlBase::_currentReference private
Current carrot reference
Definition at line 125 of file ControlBase.hpp.
Referenced by ControlBase(), getCurrentReference(), and trajPointCb().
std::array<double, 3> uav_controller::ControlBase::_currentVelocity { 0.0, 0.0, 0.0 } private
Current local velocity vector.
Definition at line 118 of file ControlBase.hpp.
Referenced by getCurrVelocity(), msfOdomCb(), and odomCb().
double uav_controller::ControlBase::_currentYaw = 0 private
Current UAV yaw
Definition at line 112 of file ControlBase.hpp.
Referenced by getCurrentYaw(), msfOdomCb(), and odomCb().
ros::Publisher uav_controller::ControlBase::_pubAttitudeSetpoint private
Definition at line 133 of file ControlBase.hpp.
Referenced by ControlBase(), and publishAttitudeTarget().
ros::Publisher uav_controller::ControlBase::_pubEulerSetpoint private
Declare all publishers.
Definition at line 132 of file ControlBase.hpp.
Referenced by ControlBase(), and publishEulerSp().
ros::Subscriber uav_controller::ControlBase::_subOdom private
Declare all subscribers
Definition at line 128 of file ControlBase.hpp.
Referenced by ControlBase().
ros::Subscriber uav_controller::ControlBase::_subReference private
Definition at line 129 of file ControlBase.hpp.
Referenced by ControlBase().
The documentation for this class was generated from the following files:
uav_ros_control/include/uav_ros_control/control/ControlBase.hpp
uav_ros_control/src/control/ControlBase.cpp