uav_ros_control: dist_control::DistanceControl Class Reference
dist_control::DistanceControl Class Reference
#include <DistanceController.hpp>
Public Member Functions
DistanceControl (ros::NodeHandle &nh)
virtual ~DistanceControl ()
void detectStateChange ()
void calculateInspectionSetpoint (double dt)
bool inInspectionState ()
void doDistanceControl (double dt)
void distParamCb (uav_ros_control::DistanceControlParametersConfig &configMsg, uint32_t level)
void distanceCb (const std_msgs::Float64ConstPtr &message)
void distanceSpOffsetCb (const std_msgs::Float64ConstPtr &message)
void distanceVelCb (const std_msgs::Float64ConstPtr &message)
void normalCb (const geometry_msgs::PoseStampedConstPtr &message)
void publishDistanceInfo ()
Public Member Functions inherited from uav_controller::CascadePID
CascadePID (ros::NodeHandle &nh)
~CascadePID ()=default
void calculateAttThrustSp (double dt)
bool activationPermission ()
void resetPositionPID ()
void resetVelocityPID ()
Public Member Functions inherited from uav_controller::ControlBase
ControlBase (ros::NodeHandle &nh)
virtual ~ControlBase ()=default
void setAttitudeSp (double roll, double pitch, double yaw)
void setThrustSp (double thrust)
const std::array< double, 3 > & getCurrPosition ()
const std::array< double, 3 > & getCurrVelocity ()
double getCurrentYaw ()
void publishAttitudeTarget (int typeMask, double yawRate=0)
void publishEulerSp ()
const trajectory_msgs::MultiDOFJointTrajectoryPoint & getCurrentReference ()
void overridePitchTarget (double newPitch)
void overrideRollTarget (double newRoll)
void overrideYawTarget (double newYaw)
Private Member Functions
void publishState ()
void publishDistSp ()
void publishDistVelSp ()
void publishDistanceToCarrot ()
bool enableInspectionCb (std_srvs::SetBool::Request &request, std_srvs::SetBool::Response &response)
void setDistReconfigureParams (uav_ros_control::DistanceControlParametersConfig &config)
void initializeParameters (ros::NodeHandle &nh)
bool inspectionEnabled ()
void deactivateInspection ()
bool inspectionRequested ()
bool inspectionFailed ()
bool manualRequested ()
Private Attributes
DistanceControlState _currState
std::unique_ptr< PID > _distancePID
std::unique_ptr< PID > _distanceVelPID
bool _inspectionEnabled
bool _inspectionRequestFailed
double _distanceMeasured
double _distanceVelocityMeasured
double _distSp
double _distSpOffset
double _distVelSp
double _planeYaw
ros::Subscriber _subDistance
ros::Subscriber _subDistanceVelocity
ros::Subscriber _subPlaneNormal
ros::Subscriber _subDistSpOffset
ros::Publisher _pubControlState
ros::Publisher _pubDistanceSp
ros::Publisher _pubDistanceVelocitySp
ros::Publisher _pubCarrotDistance
ros::ServiceServer _serviceEnableInspection
boost::recursive_mutex _distConfigMutex
dynamic_reconfigure::Server< uav_ros_control::DistanceControlParametersConfig > _distConfigServer { _distConfigMutex, ros::NodeHandle("distance_config") }
dynamic_reconfigure::Server< uav_ros_control::DistanceControlParametersConfig >::CallbackType _distParamCallback
Detailed Description
Definition at line 39 of file DistanceController.hpp.
Constructor & Destructor Documentation
dist_control::DistanceControl::DistanceControl (ros::NodeHandle & nh)
Default constructor. Used for reading ROS parameters and initalizing private variables.
Parameters
nh - given ROS node handle
Definition at line 13 of file DistanceController.cpp.
References _currState, _distanceMeasured, _distanceVelocityMeasured, _distanceVelPID, _distConfigServer, _distParamCallback, _distSp, _distSpOffset, _distVelSp, _inspectionRequestFailed, _planeYaw, _pubControlState, _pubDistanceSp, _pubDistanceVelocitySp, _serviceEnableInspection, _subDistance, _subDistanceVelocity, _subDistSpOffset, _subPlaneNormal, distanceCb(), distanceSpOffsetCb(), distanceVelCb(), distParamCb(), enableInspectionCb(), initializeParameters(), dist_control::MANUAL, normalCb(), and setDistReconfigureParams().
   : _distancePID{ new PID("Distance") }, _distanceVelPID{ new PID("Distance vel") },
     _distanceMeasured(-1), _distanceVelocityMeasured(0), _distVelSp(0), _distSp(-1),
     _distSpOffset(0), _inspectionRequestFailed(false), _planeYaw(0),
     _currState(DistanceControlState::MANUAL), uav_controller::CascadePID(nh)
 {
   // Initialize Class parameters
   initializeParameters(nh);
   // Setup all subscribers
   _subDistance =
     nh.subscribe("plane/distance", 1, &dist_control::DistanceControl::distanceCb, this);
   _subDistanceVelocity = nh.subscribe(
     "plane/distance_vel", 1, &dist_control::DistanceControl::distanceVelCb, this);
   _subPlaneNormal =
     nh.subscribe("plane/normal", 1, &dist_control::DistanceControl::normalCb, this);
   _subDistSpOffset = nh.subscribe("plane/distance_sp/offset",
     1,
     &dist_control::DistanceControl::distanceSpOffsetCb,
     this);
   // Setup all publishers
   _pubControlState = nh.advertise<std_msgs::Int32>("plane/control_state", 1);
   _pubDistanceSp = nh.advertise<std_msgs::Float64>("plane/distance_sp", 1);
   _pubDistanceVelocitySp = nh.advertise<std_msgs::Float64>("plane/distance_vel_sp", 1);
   _serviceEnableInspection = nh.advertiseService(
     "plane/inspection_mode", &dist_control::DistanceControl::enableInspectionCb, this);
   // Setup dynamic reconfigure server
   uav_ros_control::DistanceControlParametersConfig distConfig;
   setDistReconfigureParams(distConfig);
   _distConfigServer.updateConfig(distConfig);
   _distParamCallback =
     boost::bind(&dist_control::DistanceControl::distParamCb, this, _1, _2);
   _distConfigServer.setCallback(_distParamCallback);
 }
dist_control::DistanceControl::~DistanceControl () virtual
Definition at line 51 of file DistanceController.cpp.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
void dist_control::DistanceControl::calculateInspectionSetpoint (double dt)
Calculate target attitude setpoint while in inspection mode. During Inspection mode UAV is controlled using "Carrot commands" i.e. position control.
Parameters
dt - Given discretization time.
Definition at line 185 of file DistanceController.cpp.
References doDistanceControl().
Referenced by dist_control::runDefault().
 {
   doDistanceControl(dt);
 }
void dist_control::DistanceControl::deactivateInspection () private
Perform all necessary steps in order to deactivate inspection mode.
Definition at line 157 of file DistanceController.cpp.
References _currState, _distancePID, _distanceVelPID, _inspectionEnabled, dist_control::MANUAL, uav_controller::CascadePID::resetPositionPID(), and uav_controller::CascadePID::resetVelocityPID().
Referenced by detectStateChange(), and enableInspectionCb().
 {
   _currState = DistanceControlState::MANUAL;
   _inspectionEnabled = false;
   // Reset all PIDs
   _distancePID->resetIntegrator();
   _distanceVelPID->resetIntegrator();
   resetPositionPID();
   resetVelocityPID();
   ROS_WARN("Inspection mode deactivated successfully.");
 }
void dist_control::DistanceControl::detectStateChange ()
Change the state back to manual if received distance is invalid. Change the state to inspection mode if appropriate joystick command is given.
Definition at line 121 of file DistanceController.cpp.
References _currState, _distanceMeasured, _distSp, _inspectionRequestFailed, deactivateInspection(), dist_control::INSPECTION, inspectionFailed(), inspectionRequested(), and manualRequested().
Referenced by enableInspectionCb(), and dist_control::runDefault().
 {
   // If we're in inspection mode and received distance is invalid
   // then deactivate inspection mode !
   if (inspectionFailed()) {
     ROS_FATAL("Inspection mode failed - invalid distance");
     deactivateInspection();
     _inspectionRequestFailed = true;
     return;
   }
   // Check if user wants to go to inspection mode
   if (inspectionRequested() && !_inspectionRequestFailed) {
     ROS_DEBUG("Inspection mode requested.");
     // Check if current distance is valid
     if (_distanceMeasured < 0) {
       ROS_FATAL("Unable to enter inspection mode.");
       _inspectionRequestFailed = true;
       return;
     }
     ROS_INFO(
       "Inspection activation successful-following distance %.2f", _distanceMeasured);
     _distSp = _distanceMeasured;
     _currState = DistanceControlState::INSPECTION;
     return;
   }
   // Check if user wants to go back to manual mode
   if (manualRequested()) {
     ROS_WARN("Manual mode entered.");
     _inspectionRequestFailed = false;
     deactivateInspection();
   }
 }
void dist_control::DistanceControl::distanceCb (const std_msgs::Float64ConstPtr & message)
Distance callback function.
Definition at line 88 of file DistanceController.cpp.
References _distanceMeasured.
Referenced by DistanceControl().
 {
   _distanceMeasured = message->data;
 }
void dist_control::DistanceControl::distanceSpOffsetCb (const std_msgs::Float64ConstPtr & message)
Distance setpoint offset callback
Definition at line 100 of file DistanceController.cpp.
References _distSpOffset.
Referenced by DistanceControl().
 {
   _distSpOffset = message->data;
 }
void dist_control::DistanceControl::distanceVelCb (const std_msgs::Float64ConstPtr & message)
Distance velocity callback function.
Definition at line 93 of file DistanceController.cpp.
References _distanceVelocityMeasured.
Referenced by DistanceControl().
 {
   _distanceVelocityMeasured = message->data;
 }
void dist_control::DistanceControl::distParamCb (uav_ros_control::DistanceControlParametersConfig & configMsg, uint32_t level)
Callback function used for setting various parameters.
Definition at line 243 of file DistanceController.cpp.
References _distancePID, and _distanceVelPID.
Referenced by DistanceControl().
 {
   ROS_WARN("DistanceControl::parametersCallback");
   _distancePID->set_kp(configMsg.k_p_dist);
   _distancePID->set_kd(configMsg.k_d_dist);
   _distancePID->set_ki(configMsg.k_i_dist);
   _distancePID->set_lim_high(configMsg.lim_high_dist);
   _distancePID->set_lim_low(configMsg.lim_low_dist);
   _distanceVelPID->set_kp(configMsg.k_p_vdist);
   _distanceVelPID->set_kd(configMsg.k_d_vdist);
   _distanceVelPID->set_ki(configMsg.k_i_vdist);
   _distanceVelPID->set_lim_high(configMsg.lim_high_vdist);
   _distanceVelPID->set_lim_low(configMsg.lim_low_vdist);
 }
void dist_control::DistanceControl::doDistanceControl (double dt)
Perform distance control. Set attitude setpoint according to the current distance.
Definition at line 190 of file DistanceController.cpp.
References _distanceMeasured, _distancePID, _distanceVelocityMeasured, _distanceVelPID, _distSp, _distSpOffset, _distVelSp, _planeYaw, uav_controller::CascadePID::calculateAttThrustSp(), nonlinear_filters::deadzone(), DIST_SP_DEADZONE, uav_controller::ControlBase::getCurrentYaw(), uav_controller::ControlBase::overridePitchTarget(), and uav_controller::ControlBase::overrideYawTarget().
Referenced by calculateInspectionSetpoint().
 {
   calculateAttThrustSp(dt);
   // update distance setpoint
   _distSp -=
     nonlinear_filters::deadzone(_distSpOffset, -DIST_SP_DEADZONE, DIST_SP_DEADZONE);
   // Calculate pitch setpoint using measured distance
   _distVelSp = _distancePID->compute(_distSp, _distanceMeasured, dt);
   double pitch = -_distanceVelPID->compute(_distVelSp, _distanceVelocityMeasured, dt);
   double yaw = getCurrentYaw() - _planeYaw;// TODO: Minus ili plus
   overridePitchTarget(pitch);
   overrideYawTarget(yaw);
 }
bool dist_control::DistanceControl::enableInspectionCb (std_srvs::SetBool::Request & request, std_srvs::SetBool::Response & response) private
Inspection enable service callback.
Definition at line 56 of file DistanceController.cpp.
References _inspectionEnabled, deactivateInspection(), detectStateChange(), and inInspectionState().
Referenced by DistanceControl().
 {
   // If user wants to disable inspection
   if (!request.data) {
     ROS_WARN("DistanceControl - deactivation request recieved");
     deactivateInspection();
     response.message = "Deactivation request successful";
     response.success = false;
     return true;
   }
   // User wants to activate inspection
   _inspectionEnabled = true;
   detectStateChange();
   // Report if state was successfully changed
   if (inInspectionState()) {
     ROS_INFO("DistanceControl - enabled");
     response.message = "Successfully entered inspection state";
     response.success = true;
   } else {
     ROS_FATAL("DistanceControl - unable to enter inspection");
     response.message = "Unable to enter inspection state";
     response.success = false;
     _inspectionEnabled = false;
   }
   return true;
 }
bool dist_control::DistanceControl::inInspectionState ()
Return true if in inspection state, otherwise false.
Definition at line 214 of file DistanceController.cpp.
References _currState, and dist_control::INSPECTION.
Referenced by enableInspectionCb(), publishState(), and dist_control::runDefault().
 {
   return _currState == DistanceControlState::INSPECTION;
 }
void dist_control::DistanceControl::initializeParameters (ros::NodeHandle & nh) private
Initialize parameters.
Definition at line 235 of file DistanceController.cpp.
References _distancePID, _distanceVelPID, DIST_PID_PARAMS, and DISTVEL_PID_PARAMS.
Referenced by DistanceControl().
 {
   ROS_WARN("DistanceControl::initializeParameters()");
   _distancePID->initializeParameters(nh, DIST_PID_PARAMS);
   _distanceVelPID->initializeParameters(nh, DISTVEL_PID_PARAMS);
 }
bool dist_control::DistanceControl::inspectionEnabled () private
From the current Joy message determine if inspection if not.
Definition at line 280 of file DistanceController.cpp.
References _inspectionEnabled.
Referenced by inspectionRequested(), and manualRequested().
 { return _inspectionEnabled; }
bool dist_control::DistanceControl::inspectionFailed () private
Returns true if inspection failed, otherwise return false.
Definition at line 224 of file DistanceController.cpp.
References _currState, _distanceMeasured, and dist_control::INSPECTION.
Referenced by detectStateChange().
 {
   return _currState == DistanceControlState::INSPECTION && _distanceMeasured < 0;
 }
bool dist_control::DistanceControl::inspectionRequested () private
Returns true if inspection is requested, otherwise return false.
Definition at line 219 of file DistanceController.cpp.
References _currState, inspectionEnabled(), and dist_control::MANUAL.
Referenced by detectStateChange().
 {
   return inspectionEnabled() && _currState == DistanceControlState::MANUAL;
 }
bool dist_control::DistanceControl::manualRequested () private
Returns true if manual mode is requested, otherwise return false.
Definition at line 229 of file DistanceController.cpp.
References _currState, _inspectionRequestFailed, dist_control::INSPECTION, and inspectionEnabled().
Referenced by detectStateChange().
 {
   return !inspectionEnabled()
          && (_currState == DistanceControlState::INSPECTION || _inspectionRequestFailed);
 }
void dist_control::DistanceControl::normalCb (const geometry_msgs::PoseStampedConstPtr & message)
Plane normal callback function.
Definition at line 106 of file DistanceController.cpp.
References _planeYaw, util::calculateYaw(), and util::wrapMinMax().
Referenced by DistanceControl().
 {
   _planeYaw = util::calculateYaw(message->pose.orientation.x,
     message->pose.orientation.y,
     message->pose.orientation.z,
     message->pose.orientation.w);
   // Check in which direction is plane normal facing
   double xComponent = cos(_planeYaw);
   if (xComponent < 0) _planeYaw += M_PI;
   _planeYaw = util::wrapMinMax(_planeYaw, -M_PI, M_PI);
 }
void dist_control::DistanceControl::publishDistanceInfo ()
Publish various distance control algorithm information.
Definition at line 282 of file DistanceController.cpp.
References publishDistSp(), publishDistVelSp(), and publishState().
Referenced by dist_control::runDefault().
 {
   publishState();
   publishDistSp();
   publishDistVelSp();
 }
void dist_control::DistanceControl::publishDistanceToCarrot () private
Publish distance to carrot.
void dist_control::DistanceControl::publishDistSp () private
Publish distance setpoint as a std_msgs::Float64 message.
Definition at line 207 of file DistanceController.cpp.
References _distSp, and _pubDistanceSp.
Referenced by publishDistanceInfo().
 {
   std_msgs::Float64 newMessage;
   newMessage.data = _distSp;
   _pubDistanceSp.publish(newMessage);
 }
void dist_control::DistanceControl::publishDistVelSp () private
Publish distance velocity setpoint as a Float64 ROS message.
Definition at line 178 of file DistanceController.cpp.
References _distVelSp, and _pubDistanceVelocitySp.
Referenced by publishDistanceInfo().
 {
   std_msgs::Float64 newMessage;
   newMessage.data = _distVelSp;
   _pubDistanceVelocitySp.publish(newMessage);
 }
void dist_control::DistanceControl::publishState () private
Publish current control state.
Definition at line 170 of file DistanceController.cpp.
References _pubControlState, and inInspectionState().
Referenced by publishDistanceInfo().
 {
   // Publish 0 for manual state and 1 for inspection state
   std_msgs::Int32 newMessage;
   newMessage.data = inInspectionState() ? 1 : 0;
   _pubControlState.publish(newMessage);
 }
void dist_control::DistanceControl::setDistReconfigureParams (uav_ros_control::DistanceControlParametersConfig & config) private
Set reconfigure parameters in the given config object.
Definition at line 262 of file DistanceController.cpp.
References _distancePID, and _distanceVelPID.
Referenced by DistanceControl().
 {
   ROS_WARN("DistanceControl::setReconfigureParameters");
   config.k_p_dist = _distancePID->get_kp();
   config.k_i_dist = _distancePID->get_ki();
   config.k_d_dist = _distancePID->get_kd();
   config.lim_low_dist = _distancePID->get_lim_low();
   config.lim_high_dist = _distancePID->get_lim_high();
   config.k_p_vdist = _distanceVelPID->get_kp();
   config.k_i_vdist = _distanceVelPID->get_ki();
   config.k_d_vdist = _distanceVelPID->get_kd();
   config.lim_low_vdist = _distanceVelPID->get_lim_low();
   config.lim_high_vdist = _distanceVelPID->get_lim_high();
 }
Field Documentation
DistanceControlState dist_control::DistanceControl::_currState private
Current control state
Definition at line 173 of file DistanceController.hpp.
Referenced by deactivateInspection(), detectStateChange(), DistanceControl(), inInspectionState(), inspectionFailed(), inspectionRequested(), and manualRequested().
double dist_control::DistanceControl::_distanceMeasured private
Current distance measured value. Used both in sim and real mode.
Definition at line 188 of file DistanceController.hpp.
Referenced by detectStateChange(), distanceCb(), DistanceControl(), doDistanceControl(), and inspectionFailed().
std::unique_ptr<PID> dist_control::DistanceControl::_distancePID private
Distance PID controller
Definition at line 176 of file DistanceController.hpp.
Referenced by deactivateInspection(), distParamCb(), doDistanceControl(), initializeParameters(), and setDistReconfigureParams().
double dist_control::DistanceControl::_distanceVelocityMeasured private
Currently measured distance velocity. Used both in sim and real mode.
Definition at line 191 of file DistanceController.hpp.
Referenced by DistanceControl(), distanceVelCb(), and doDistanceControl().
std::unique_ptr<PID> dist_control::DistanceControl::_distanceVelPID private
Distance velocity PID controller
Definition at line 179 of file DistanceController.hpp.
Referenced by deactivateInspection(), DistanceControl(), distParamCb(), doDistanceControl(), initializeParameters(), and setDistReconfigureParams().
boost::recursive_mutex dist_control::DistanceControl::_distConfigMutex private
Define Dynamic Reconfigure parameters
Definition at line 221 of file DistanceController.hpp.
dynamic_reconfigure::Server<uav_ros_control::DistanceControlParametersConfig> dist_control::DistanceControl::_distConfigServer { _distConfigMutex, ros::NodeHandle("distance_config") } private
Definition at line 223 of file DistanceController.hpp.
Referenced by DistanceControl().
dynamic_reconfigure::Server< uav_ros_control::DistanceControlParametersConfig>::CallbackType dist_control::DistanceControl::_distParamCallback private
Definition at line 225 of file DistanceController.hpp.
Referenced by DistanceControl().
double dist_control::DistanceControl::_distSp private
Distance setpoint value
Definition at line 194 of file DistanceController.hpp.
Referenced by detectStateChange(), DistanceControl(), doDistanceControl(), and publishDistSp().
double dist_control::DistanceControl::_distSpOffset private
Distance setpoint offset value
Definition at line 197 of file DistanceController.hpp.
Referenced by DistanceControl(), distanceSpOffsetCb(), and doDistanceControl().
double dist_control::DistanceControl::_distVelSp private
Distance velocity setpoint value.
Definition at line 200 of file DistanceController.hpp.
Referenced by DistanceControl(), doDistanceControl(), and publishDistVelSp().
bool dist_control::DistanceControl::_inspectionEnabled private
User enabled the inspection
Definition at line 182 of file DistanceController.hpp.
Referenced by deactivateInspection(), enableInspectionCb(), and inspectionEnabled().
bool dist_control::DistanceControl::_inspectionRequestFailed private
True if inspection state was requested and denied, false otherwise.
Definition at line 185 of file DistanceController.hpp.
Referenced by detectStateChange(), DistanceControl(), and manualRequested().
double dist_control::DistanceControl::_planeYaw private
Yaw of the plane normal with respect to UAV base frame.
Definition at line 203 of file DistanceController.hpp.
Referenced by DistanceControl(), doDistanceControl(), and normalCb().
ros::Publisher dist_control::DistanceControl::_pubCarrotDistance private
Definition at line 215 of file DistanceController.hpp.
ros::Publisher dist_control::DistanceControl::_pubControlState private
Define all ROS publishers.
Definition at line 212 of file DistanceController.hpp.
Referenced by DistanceControl(), and publishState().
ros::Publisher dist_control::DistanceControl::_pubDistanceSp private
Definition at line 213 of file DistanceController.hpp.
Referenced by DistanceControl(), and publishDistSp().
ros::Publisher dist_control::DistanceControl::_pubDistanceVelocitySp private
Definition at line 214 of file DistanceController.hpp.
Referenced by DistanceControl(), and publishDistVelSp().
ros::ServiceServer dist_control::DistanceControl::_serviceEnableInspection private
Define all the services
Definition at line 218 of file DistanceController.hpp.
Referenced by DistanceControl().
ros::Subscriber dist_control::DistanceControl::_subDistance private
Define all ROS subscribers.
Definition at line 206 of file DistanceController.hpp.
Referenced by DistanceControl().
ros::Subscriber dist_control::DistanceControl::_subDistanceVelocity private
Definition at line 207 of file DistanceController.hpp.
Referenced by DistanceControl().
ros::Subscriber dist_control::DistanceControl::_subDistSpOffset private
Definition at line 209 of file DistanceController.hpp.
Referenced by DistanceControl().
ros::Subscriber dist_control::DistanceControl::_subPlaneNormal private
Definition at line 208 of file DistanceController.hpp.
Referenced by DistanceControl().
The documentation for this class was generated from the following files:
uav_ros_control/include/uav_ros_control/control/DistanceController.hpp
uav_ros_control/src/control/DistanceController.cpp