uav_ros_control: ros_util::TopicHandler< T > Class Template Reference
ros_util::TopicHandler< T > Class Template Reference
#include <Util.hpp>
Public Member Functions
TopicHandler (ros::NodeHandle &t_nh, const std::string &t_topicName, const double t_timeoutDuration=2)
const T & getData ()
bool isResponsive ()
bool isMessageRecieved ()
Private Member Functions
void callback (const T &msg)
void watchdog_callback (const ros::TimerEvent &e)
Private Attributes
ros::Timer m_watchdogTimer
double m_topicTimeout
double m_lastMessgeTime
bool m_isResponsive
bool m_messageRecieved
ros::Subscriber m_subT
T m_data
const std::string m_topicName
Detailed Description
template<class T>
class ros_util::TopicHandler< T >
Definition at line 46 of file Util.hpp.
Constructor & Destructor Documentation
template<class T> ros_util::TopicHandler< T >::TopicHandler (ros::NodeHandle & t_nh, const std::string & t_topicName, const double t_timeoutDuration = 2) inline
Definition at line 49 of file Util.hpp.
     : m_topicName(t_topicName), m_topicTimeout(t_timeoutDuration), m_lastMessgeTime(0),
       m_isResponsive(false), m_messageRecieved(false)
   {
     m_subT = t_nh.subscribe(m_topicName, 1, &TopicHandler::callback, this);
     if (t_timeoutDuration > 0) {
       m_watchdogTimer = t_nh.createTimer(
         ros::Duration(t_timeoutDuration), &TopicHandler::watchdog_callback, this);
     }
   }
Member Function Documentation
template<class T> void ros_util::TopicHandler< T >::callback (const T & msg) inline private
Definition at line 71 of file Util.hpp.
Referenced by ros_util::TopicHandler< mavros_msgs::HomePosition >::TopicHandler().
   {
     m_data = std::move(msg);
     m_lastMessgeTime = ros::Time::now().toSec();
     m_messageRecieved = true;
   }
template<class T> const T& ros_util::TopicHandler< T >::getData () inline
Definition at line 63 of file Util.hpp.
Referenced by uav_reference::CarrotReference::landServiceCb(), uav_reference::CarrotReference::takeoffServiceCb(), and uav_reference::CarrotReference::updateCarrotStatus().
 { return m_data; }
template<class T> bool ros_util::TopicHandler< T >::isMessageRecieved () inline
Definition at line 68 of file Util.hpp.
 { return m_messageRecieved; }
template<class T> bool ros_util::TopicHandler< T >::isResponsive () inline
Definition at line 66 of file Util.hpp.
 { return m_isResponsive; }
template<class T> void ros_util::TopicHandler< T >::watchdog_callback (const ros::TimerEvent & e) inline private
Definition at line 78 of file Util.hpp.
Referenced by ros_util::TopicHandler< mavros_msgs::HomePosition >::TopicHandler().
   {
     double elapsedTime = ros::Time::now().toSec() - m_lastMessgeTime;
     if (elapsedTime > m_topicTimeout) {
       m_isResponsive = false;
       ROS_FATAL_STREAM("Topic: [" << m_topicName << "] unresponsive.");
     } else {
       m_isResponsive = true;
     }
   }
Field Documentation
template<class T> T ros_util::TopicHandler< T >::m_data private
Definition at line 94 of file Util.hpp.
template<class T> bool ros_util::TopicHandler< T >::m_isResponsive private
Definition at line 91 of file Util.hpp.
template<class T> double ros_util::TopicHandler< T >::m_lastMessgeTime private
Definition at line 90 of file Util.hpp.
template<class T> bool ros_util::TopicHandler< T >::m_messageRecieved private
Definition at line 91 of file Util.hpp.
template<class T> ros::Subscriber ros_util::TopicHandler< T >::m_subT private
Definition at line 93 of file Util.hpp.
template<class T> const std::string ros_util::TopicHandler< T >::m_topicName private
Definition at line 95 of file Util.hpp.
template<class T> double ros_util::TopicHandler< T >::m_topicTimeout private
Definition at line 90 of file Util.hpp.
template<class T> ros::Timer ros_util::TopicHandler< T >::m_watchdogTimer private
Definition at line 89 of file Util.hpp.
The documentation for this class was generated from the following file:
uav_ros_control/include/uav_ros_control/filters/Util.hpp