uav_ros_control: dist_control Namespace Reference
dist_control Namespace Reference
Data Structures
class DistanceControl
Enumerations
enum DistanceControlState { MANUAL, INSPECTION }
Functions
void runDefault (dist_control::DistanceControl &cc, ros::NodeHandle &nh)
Enumeration Type Documentation
enum dist_control::DistanceControlState
Enumerator
MANUAL
User controls the UAV manually using joystick commands.
INSPECTION
User controls the UAV while it performs inspection, maintaining the distance from the callback function feedback loop.
Definition at line 26 of file DistanceController.hpp.
{
   MANUAL,
   INSPECTION
 };
Function Documentation
void dist_control::runDefault (dist_control::DistanceControl & cc, ros::NodeHandle & nh)
Run default Distance Control algorithm
Parameters
cc - Reference to CarrotControl object
nh - Given NodeHandle
simMode - true if simulation mode is enabled, otherwise false
Definition at line 289 of file DistanceController.cpp.
References uav_controller::CascadePID::calculateAttThrustSp(), dist_control::DistanceControl::calculateInspectionSetpoint(), dist_control::DistanceControl::detectStateChange(), dist_control::DistanceControl::inInspectionState(), uav_controller::MASK_IGNORE_RP_RATE, uav_controller::ControlBase::publishAttitudeTarget(), dist_control::DistanceControl::publishDistanceInfo(), and uav_controller::ControlBase::publishEulerSp().
Referenced by main().
 {
   // Setup loop rate
   double rate = 50;
   ros::Rate loopRate(rate);
   double dt = 1.0 / rate;
   ROS_INFO("dist_control::runDeafult() - Setting rate to %.2f", rate);
   // Start the main loop
   while (ros::ok()) {
     ros::spinOnce();
     dc.detectStateChange();
     // Do  Inspection
     if (dc.inInspectionState()) dc.calculateInspectionSetpoint(dt);
     // If not in inspection state go to attitude control
     else
       dc.calculateAttThrustSp(dt);
     // Publish attitude setpoint
     dc.publishAttitudeTarget(uav_controller::MASK_IGNORE_RP_RATE);
     // Publish other information
     dc.publishDistanceInfo();
     dc.publishEulerSp();
     loopRate.sleep();
   }
 }