uav_ros_control: uav_reference Namespace Reference
uav_reference Namespace Reference
Namespaces
traj_gen
Data Structures
class CarrotReference
class GeoFence
class JoyControlInput
Functions
void runDefault (uav_reference::CarrotReference &cc, ros::NodeHandle &nh)
void runDefault (uav_reference::GeoFence &gf, ros::NodeHandle &nh)
Function Documentation
void uav_reference::runDefault (uav_reference::GeoFence & gf, ros::NodeHandle & nh)
Definition at line 202 of file GeoFence.cpp.
 {
   ros::spin();
 }
void uav_reference::runDefault (uav_reference::CarrotReference & cc, ros::NodeHandle & nh)
Run default Carrot Reference publishing node program.
Parameters
cc - Reference to CarrotReference object
nh - Given NodeHandle
Definition at line 436 of file CarrotReference.cpp.
References uav_reference::CarrotReference::publishCarrotSetpoint(), uav_reference::CarrotReference::updateCarrot(), and uav_reference::CarrotReference::updateCarrotStatus().
Referenced by main().
 {
   double rate = 50;
   ros::Rate loopRate(rate);
   while (ros::ok()) {
     ros::spinOnce();
     carrotRefObj.updateCarrotStatus();
     carrotRefObj.updateCarrot();
     carrotRefObj.publishCarrotSetpoint();
     loopRate.sleep();
   }
 }