uav_ros_control: util Namespace Reference
util Namespace Reference
Functions
double wrapMinMax (double x, double min, double max)
double calculateYaw (double qx, double qy, double qz, double qw)
Function Documentation
double util::calculateYaw (double qx, double qy, double qz, double qw)
Calculates yaw angle from given quaternion components.
Definition at line 60 of file NonlinearFilters.cpp.
Referenced by uav_controller::ControlBase::msfOdomCb(), dist_control::DistanceControl::normalCb(), uav_controller::ControlBase::odomCb(), uav_reference::CarrotReference::odomCb(), and uav_reference::CarrotReference::positionRefCb().
 {
     return atan2(
         2 * (qw * qz + qx * qy),
         qw * qw + qx * qx - qy * qy - qz * qz);
 }
double util::wrapMinMax (double x, double min, double max)
wrap x -> [min,max)
Definition at line 55 of file NonlinearFilters.cpp.
References wrapMax().
Referenced by dist_control::DistanceControl::normalCb(), and uav_reference::CarrotReference::updateCarrotYaw().
 {
     return min + wrapMax(x - min, max - min);
 }